server:
  port: 8080
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username:
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  #Allow Spring to spot put/delete requests from the html forms
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  main:
    #Turn off the logo
    banner-mode: off
  #Set database connection properties
  datasource:
    url: jdbc:mysql://localhost:3306/unihub
    username: root
    password: Kenan@sql#16
  #Add actuators
  management:
    endpoints:
      web:
        exposure:
          include: "*"